(ns gen-golden
  "Regenerate the frozen golden bytes.

  Run ONLY when the wire format is deliberately being changed:

    bin/regen-golden

  (Not `clj -M:test -m gen-golden` — the :test alias sets :main-opts, which
  overrides -m, so that silently runs the test suite instead of this.)

  cljfmt checks the generated file too, so the script runs `clj -M:ffix` after
  writing; skipping that makes the format job fail.

  Then read the diff to test/boring/golden_v1.cljc line by line. Every changed
  line is a wire-format change; if you did not intend one, you have found a
  bug. Committing a regenerated file without reading the diff defeats the
  entire mechanism."
  (:require [clojure.string :as str]
            [boring.core :as boring]
            [boring.golden :as g]))

(defn- hex [^bytes bs]
  (str/join (map #(format "%02x" %) bs)))

(defn- render-entries
  "Entries at `indent` spaces.

  PARAMETERISED because the two maps sit at different depths -- `jvm-only` is
  nested inside a reader conditional -- and emitting both at three spaces put
  the generator in permanent conflict with `clojure -M:format`: regenerating
  un-formatted the file, so the CI format job was red, and a job that is always
  red is a job nobody reads."
  [corpus indent]
  (let [pad (apply str (repeat indent \space))]
    (str/join "\n"
              (for [[label value opts] corpus]
                (str pad (format "%-22s %s" (pr-str label)
                                 (pr-str (hex (boring/encode value opts)))))))))

(defn -main [& _]
  (let [out "test/boring/golden_v1.cljc"
        content
        (str ";; GENERATED by dev/gen_golden.clj — DO NOT EDIT BY HAND.\n"
             ";;\n"
             ";; These are frozen wire bytes. A diff here is a wire-format change:\n"
             ";; either deliberate and documented, or a bug. There is no third case.\n"
             ";; See boring.golden for what the corpus covers and why it is split.\n"
             "(ns boring.golden-v1)\n"
             "\n"
             "(def portable\n"
             "  {" (str/triml (render-entries g/portable 3)) "})\n"
             "\n"
             "#?(:clj\n"
             "   (def jvm-only\n"
             "     {" (str/triml (render-entries g/jvm-only 6)) "}))\n")]
    (spit out content)
    (println "wrote" out)
    (println " " (count g/portable) "portable +" (count g/jvm-only) "jvm-only vectors")))
